version: "3.9" 
services: 
  postgres: 
    image: postgres:16-alpine 
    environment: 
      POSTGRES_USER: rust 
      POSTGRES_PASSWORD: rust 
      POSTGRES_DB: rust_api_lab 
    ports: ["5432:5432"] 
    volumes: ["pgdata:/var/lib/postgresql/data"] 
volumes: 
  pgdata: 
