[package]
<<<<<<< HEAD
name = "api"
=======
name    = "api"
>>>>>>> d624ae11aed19a06cc2a02386e38faa5ea737fef
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls", "macros"] }
dotenv = "0.15"
actix-cors = "0.7"
db = { path = "../db" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
=======
actix-web = "4.4"
serde     = { version = "1.0", features = ["derive"] }
dotenv    = "0.15"
env_logger= "0.10"
log       = "0.4"
db        = { path = "../db" }
sqlx      = { version = "0.7", features = ["postgres", "runtime-tokio-rustls", "chrono"] }
chrono    = { version = "0.4", features = ["serde"] }
>>>>>>> d624ae11aed19a06cc2a02386e38faa5ea737fef
